# Generated by Django 2.2.3 on 2019-12-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de programacion'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre del fichero'),
        ),
    ]
