# Generated by Django 2.2.3 on 2019-12-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20191204_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dia programado')),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='Dia de la semana')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.AddField(
            model_name='message',
            name='week_day',
            field=models.ManyToManyField(to='messenger.WeekDay'),
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.ManyToManyField(to='messenger.Date'),
        ),
    ]
