# Generated by Django 2.2.3 on 2019-12-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20191204_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-name'], 'verbose_name': 'mensaje', 'verbose_name_plural': 'mensajes'},
        ),
    ]
