# Generated by Django 2.2.3 on 2019-12-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_auto_20191204_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['-date'], 'verbose_name': 'date', 'verbose_name_plural': 'date'},
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(unique=True, verbose_name='Dia programado'),
        ),
    ]
