# Generated by Django 2.2.3 on 2019-12-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20191204_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.ManyToManyField(blank=True, null=True, to='messenger.Date'),
        ),
    ]
