# Generated by Django 2.2.3 on 2019-12-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_auto_20191204_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='week_day',
            field=models.ManyToManyField(blank=True, null=True, to='messenger.WeekDay'),
        ),
    ]
