# Generated by Django 2.2.3 on 2019-12-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_auto_20191204_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
